/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rmi_practica2;

import java.io.File;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
/**
 *
 * @author Erick C
 */
public class ClientFrame extends javax.swing.JFrame {

    boolean loggedUser=false;
    Registry registry;
    //Registry registry = LocateRegistry.getRegistry(8888);
    //ChatInterface server = (ChatInterface)registry.lookup("ejemplo");
    String filePath="";
    ChatInterface server;
    public ClientFrame() {
        initComponents();
        try {
            registry = LocateRegistry.getRegistry(8888);
            server = (ChatInterface)registry.lookup("ejemplo");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_create_file = new javax.swing.JButton();
        PopUp_menu_show_text = new javax.swing.JPopupMenu();
        jb_refresh_tree = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Panel_Files = new javax.swing.JTree();
        tf_selected_file = new javax.swing.JTextField();
        jb_read_file = new javax.swing.JButton();
        jb_write_overwrite_data = new javax.swing.JButton();
        tf_create_file_name = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_data = new javax.swing.JTextArea();
        jb_create_file1 = new javax.swing.JButton();
        jb_Initialize = new javax.swing.JButton();

        jb_create_file.setText("Crear Archivo");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_refresh_tree.setText("Refrescar");
        jb_refresh_tree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_refresh_treeMouseClicked(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Files");
        jt_Panel_Files.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_Panel_Files.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_Panel_FilesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_Panel_Files);

        tf_selected_file.setEditable(false);
        tf_selected_file.setText("-- No data --");
        tf_selected_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_selected_fileActionPerformed(evt);
            }
        });

        jb_read_file.setText("Leer");
        jb_read_file.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_read_fileMouseClicked(evt);
            }
        });

        jb_write_overwrite_data.setText("Escribir");
        jb_write_overwrite_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_write_overwrite_dataMouseClicked(evt);
            }
        });

        ta_data.setColumns(20);
        ta_data.setRows(5);
        jScrollPane2.setViewportView(ta_data);

        jb_create_file1.setText("Crear Archivo");
        jb_create_file1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_create_file1MouseClicked(evt);
            }
        });

        jb_Initialize.setText("Init");
        jb_Initialize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_InitializeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_create_file1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_Initialize)
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_create_file_name)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                            .addComponent(jb_refresh_tree))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_selected_file, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jb_read_file)
                                .addGap(53, 53, 53)
                                .addComponent(jb_write_overwrite_data)
                                .addGap(72, 72, 72))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(61, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_refresh_tree)
                    .addComponent(tf_selected_file, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_read_file)
                    .addComponent(jb_write_overwrite_data))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(tf_create_file_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_create_file1)
                    .addComponent(jb_Initialize))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_refresh_treeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_refresh_treeMouseClicked
        // TODO add your handling code here:
        try {
            if(loggedUser){
                //String OrigenCarpeta = "./serverDocs";
                //File directorio = new File(OrigenCarpeta);
                //directorio.mkdir();
                DefaultTreeModel m = (DefaultTreeModel) jt_Panel_Files.getModel();
                m.setRoot(new DefaultMutableTreeNode("Files"));
                listarOrganizador(server.getFileData(), (DefaultMutableTreeNode) m.getRoot());
            }else{
                JOptionPane.showMessageDialog(this, "Log in first");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_refresh_treeMouseClicked

    private void tf_selected_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_selected_fileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_selected_fileActionPerformed

    private void jb_InitializeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_InitializeMouseClicked
        // TODO add your handling code here:
        try{
            if (!loggedUser) {
                loggedUser = true;
                System.out.println("Nombre:");
                String name = JOptionPane.showInputDialog(this, "Nombre");

                ChatInterface client = new Chat(name);
                String msg = "[" + client.getName() + "] conectado!";
                server.send(msg);
                System.out.println("Servicio listo");
                server.setClient(name, client);
                String user = "";
            } else {
                JOptionPane.showMessageDialog(this, "Already logged in");
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_InitializeMouseClicked

    private void jb_read_fileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_read_fileMouseClicked
        // TODO add your handling code here:
        try {
            if (loggedUser) {
                if(filePath!=""){
                    tf_selected_file.setText(filePath);
                    server.setFilePath(filePath);
                    ta_data.setText( server.leerArchivo());
                }
                
                
            } else {
                JOptionPane.showMessageDialog(this, "Already logged in");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_read_fileMouseClicked

    private void jt_Panel_FilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_Panel_FilesMouseClicked
        // TODO add your handling code here:
        try {
            if (loggedUser) {
                    //JOptionPane.showMessageDialog(this, "what");
                    int row = jt_Panel_Files.getClosestRowForLocation(evt.getX(), evt.getY());
                    jt_Panel_Files.setSelectionRow(row);
                    Object v1
                            = jt_Panel_Files.getSelectionPath().
                                    getLastPathComponent();
                    nodo_seleccionado = (DefaultMutableTreeNode) v1;
                    if (nodo_seleccionado.getUserObject() instanceof File) {
                        String data = nodo_seleccionado.toString();
                        //JOptionPane.showMessageDialog(this, data);
                        filePath=data;
                    }
                
            } else {
                JOptionPane.showMessageDialog(this, "Already logged in");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jt_Panel_FilesMouseClicked

    private void jb_create_file1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_create_file1MouseClicked
        // TODO add your handling code here:
        try{
            if(loggedUser){
                String name=tf_create_file_name.getText();
                if(server.verifyExist(name)){
                    JOptionPane.showMessageDialog(this, "File already exists");
                }else{
                    server.createFile(name);
                    tf_create_file_name.setText("");
                    JOptionPane.showMessageDialog(this, "File created. Refresh the list");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Access Denied. Can't create file");
            }
        }catch (Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jb_create_file1MouseClicked

    private void jb_write_overwrite_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_write_overwrite_dataMouseClicked
        // TODO add your handling code here:
        try {
            if(loggedUser){
                String dataExtractor= ta_data.getText();
                server.escribirArchivo(dataExtractor);
                JOptionPane.showMessageDialog(this, "Data has been overwritten");
            }else{
                JOptionPane.showMessageDialog(this, "Login required");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_write_overwrite_dataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientFrame().setVisible(true);
            }
        });
    }
    
    public void listarOrganizador(File p_raiz, DefaultMutableTreeNode nodo) {
        try {
            for (File temp : p_raiz.listFiles()) {
                if (temp.isFile()) {
//                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(temp);
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(temp);
                    nodo.add(n);
                } else {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(temp);
                    nodo.add(n);
                    listar_no_orden(temp, n);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void listar_no_orden(File p_raiz, DefaultMutableTreeNode nodo) {
        try {
            for (File temp : p_raiz.listFiles()) {
                if (temp.isFile()) {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(
                            temp.getName());
                    nodo.add(n);
                } else {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(
                            temp.getName());
                    nodo.add(n);
                    listar_no_orden(temp, n);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu PopUp_menu_show_text;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb_Initialize;
    private javax.swing.JButton jb_create_file;
    private javax.swing.JButton jb_create_file1;
    private javax.swing.JButton jb_read_file;
    private javax.swing.JButton jb_refresh_tree;
    private javax.swing.JButton jb_write_overwrite_data;
    private javax.swing.JTree jt_Panel_Files;
    private javax.swing.JTextArea ta_data;
    private javax.swing.JTextField tf_create_file_name;
    private javax.swing.JTextField tf_selected_file;
    // End of variables declaration//GEN-END:variables
    DefaultMutableTreeNode nodo_seleccionado;
}
